homeassistant:
  name: Casa Nórdica
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Madrid

default_config:

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    homeassistant.components.androidtv: info

recorder:
  purge_keep_days: 7
  auto_purge: true
  commit_interval: 30
  exclude:
    entity_globs:
      - sensor.*_linkquality
      - sensor.*_rssi
    domains:
      - updater

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

api:
frontend:
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_boolean:
  modo_cine:
    name: Modo Cine
    icon: mdi:movie
  modo_noche:
    name: Modo Noche
    icon: mdi:weather-night